image: docker:stable

build_image:
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE"
deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - cd ./deployment
    - sed -i "s|CONTAINER_IMAGE|$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA|g" deployment.yaml
    - cat deployment.yaml
    - cat service.yaml
    # - kubectl apply -f deployment.yaml -f service.yaml -n default --dry-run=client --validate=true
    # - kubectl apply -f deployment.yaml -f service.yaml -n default
